-- AlterTable
-- Achievement Bonuses
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "achievementBonusEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "achievementChoresRequired" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "achievementBonusMoneyPence" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "achievementBonusStars" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "achievementBonusType" TEXT NOT NULL DEFAULT 'both';

-- Birthday Bonuses
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "birthdayBonusEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "birthdayBonusMoneyPence" INTEGER NOT NULL DEFAULT 500;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "birthdayBonusStars" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "birthdayBonusType" TEXT NOT NULL DEFAULT 'both';

-- Perfect Week Bonus
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "perfectWeekBonusEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "perfectWeekBonusMoneyPence" INTEGER NOT NULL DEFAULT 200;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "perfectWeekBonusStars" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "perfectWeekBonusType" TEXT NOT NULL DEFAULT 'both';

-- Monthly Milestone Bonuses
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "monthlyBonusEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "monthlyBonusMoneyPence" INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "monthlyBonusStars" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "monthlyBonusType" TEXT NOT NULL DEFAULT 'both';

-- Surprise Random Bonuses
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "surpriseBonusEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "surpriseBonusChance" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "surpriseBonusMoneyPence" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "surpriseBonusStars" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "surpriseBonusType" TEXT NOT NULL DEFAULT 'both';

