-- AlterTable
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "holidayEndDate" TIMESTAMP(3);
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "holidayMode" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "holidayStartDate" TIMESTAMP(3);
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "paused" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "bonusDays" INTEGER NOT NULL DEFAULT 7;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "bonusEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "bonusMoneyPence" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "bonusStars" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "bonusType" TEXT NOT NULL DEFAULT 'both';
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "firstMissPence" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "firstMissStars" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "holidayEndDate" TIMESTAMP(3);
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "holidayMode" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "holidayStartDate" TIMESTAMP(3);
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMP(3);
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "minBalancePence" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "minBalanceStars" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "penaltyEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "penaltyType" TEXT NOT NULL DEFAULT 'both';
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "secondMissPence" INTEGER NOT NULL DEFAULT 25;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "secondMissStars" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "streakProtectionDays" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "suspendedAt" TIMESTAMP(3);
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "thirdMissPence" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "thirdMissStars" INTEGER NOT NULL DEFAULT 5;

